models/Journal.php
<?php

namespace app\models;

use yii\db\ActiveRecord;
use yii\helpers\ArrayHelper;
/**
 * This is the model class for table "journal".
 *
 * @property integer $id
 * @property integer $object_id
 * @property integer $equipment_id
 * @property integer $user_id
 * @property string $date
 * @property integer $type_id
 * @property string $description
 * @property string $media
 *
 * @property OurObject $object
 * @property string $objectName
 * @property Equipment $equipment
 * @property string $equipmentName
 * @property Users $user
 * @property string $userName
 * @property Type $type
 * @property string $typeName
 * @property Node $node
 * @property int $node_id Код узла

 */
class Journal extends ActiveRecord
{
    public $date_start;
    public $date_end;

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'journal';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['node_id', 'object_id', 'equipment_id', 'user_id', 'type_id'], 'integer'],
            [['date'], 'safe'],
            [['description', 'media'], 'string', 'max' => 255],
            [['object_id', 'equipment_id', 'date', 'type_id', 'description'], 'required'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'object_id' => 'Предприятие',
            'equipment_id' => 'Оборудование',
            'user_id' => 'Пользователь',
            'date' => 'Дата',
            'type_id' => 'Тип работ',
            'description' => 'Описание',
            'media' => 'Ссылка',
            'node_id' => 'Наименование узла',
            'objectName' => 'Предприятие',
            'equipmentName' => 'Оборудование',
            'userName' => 'Пользователь',
            'typeName' => 'Тип работ',
        ];
    }

    public function getObjectName()
    {
        return $this->object->name ?? null;
    }

    public function getEquipmentName()
    {
        return $this->equipment->name ?? null;
    }

    public function getUserName()
    {
        return $this->user->name ?? null;
    }

    public function getObject()
    {
        return $this->hasOne(OurObject::class, ['id' => 'object_id']);
    }

    public function getType()
    {
        return $this->hasOne(Type::class, ['id' => 'type_id']);
    }

    public function getTypeName()
    {
        return $this->type->name ?? null;
    }

    public function getEquipment()
    {
        return $this->hasOne(Equipment::class, ['id' => 'equipment_id']);
    }

    public function getUser()
    {
        return $this->hasOne(Users::class, ['id' => 'user_id']);
    }

    public function getNode()
    {
        return $this->hasOne(Node::class, ['id' => 'node_id']);
    }

    public static function getUsersList()
    {
        $user = Users::find()->all();
        return ArrayHelper::map($user, 'id', 'fio');
    }

    public function getEquipmentList($object_id)
    {
        $datas = EquipmentObject::find()->where(['object_id' => $object_id ])->all();
        $array = [];
        foreach($datas as $data){
            $array [] = $data->equipment_id;
        }
        $array = array_unique($array);
        $equipments = Equipment::find()->where(['id' => $array])->all();
        return ArrayHelper::map($equipments, 'id', 'name');
    }

    /**
     * @param string $rus_date Дата в формате d.m.Y
     * @return null
     */
    public static function getDateForDb($rus_date){

        if (!strstr($rus_date, '.')) return null;

        $part_date = explode('.', $rus_date);

        $pendos_date = $part_date[2] . '-' . $part_date[1] . '-' . $part_date[0];

        \Yii::info($pendos_date, 'test');

        return $pendos_date;

    }
}

controllers/JournalController.php
<?php

namespace app\controllers;

use app\models\Journal;
use app\models\JournalSearch;
use app\models\Node;
use app\models\OurObject;
use app\models\Type;
use app\models\UploadForm;
use app\models\Users;
use PhpOffice\PhpSpreadsheet\IOFactory;
use Yii;
use yii\data\ActiveDataProvider;
use yii\filters\VerbFilter;
use yii\helpers\Html;
use yii\helpers\VarDumper;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\web\Response;
use app\models\EquipmentObject;
use app\models\Equipment;
use yii\web\UploadedFile;

/**
 * JournalController implements the CRUD actions for Journal model.
 */
class JournalController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => \yii\filters\AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                    'bulk-delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all Journal models.
     * @return mixed
     */
    public function actionIndex()
    {
        $request = Yii::$app->request;

        $searchModel = new JournalSearch();

        if ($request->isPost) {
            //Если передаются параметры фильтрации
            $dataProvider = new ActiveDataProvider([
                'query' => Journal::find(),
            ]);

            if ($request->post('date_start') && $request->post('date_end')) {
                $dataProvider->query->andWhere([
                    'BETWEEN',
                    'date',
                    Journal::getDateForDb($request->post('date_start')) . ' 00:00:00',
                    Journal::getDateForDb($request->post('date_end')) . ' 23:59:59'
                ]);
            }

            if ($request->post('object')) {
                $dataProvider->query->andWhere(['object_id' => $request->post('object')]);
            }

            if ($request->post('equipment')) {
                $dataProvider->query->andWhere(['equipment_id' => $request->post('equipment')]);
            }

            if ($request->post('type')) {
                $dataProvider->query->andWhere(['type_id' => $request->post('type')]);
            }

            $dataProvider->pagination= false;

        } else {
            $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        }


        return $this->render('index', [
            'dataProvider' => $dataProvider,
            'searchModel' => $searchModel,
        ]);
    }

    public function actionLists($id)
    {
        $datas = EquipmentObject::find()->where(['object_id' => $id])->all();
        $array = [];
        foreach ($datas as $data) {
            $array [] = $data->equipment_id;
        }
        $array = array_unique($array);

        foreach ($array as $data) {
            $equipment = Equipment::findOne($data);
            echo "<option value = '" . $equipment->id . "'>" . $equipment->name . "</option>";
        }
    }

    /**
     * Displays a single Journal model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException
     */
    public function actionView($id)
    {
        $request = Yii::$app->request;
        if ($request->isAjax) {
            Yii::$app->response->format = Response::FORMAT_JSON;
            return [
                'title' => "Журнал",
                'size' => 'normal',
                'content' => $this->renderAjax('view', [
                    'model' => $this->findModel($id),
                ]),
                'footer' => Html::button('Отмена', ['class' => 'btn btn-default pull-left', 'data-dismiss' => "modal"]) .
                    Html::a('Изменить', ['update', 'id' => $id], ['class' => 'btn btn-primary', 'role' => 'modal-remote'])
            ];
        } else {
            return $this->render('view', [
                'model' => $this->findModel($id),
            ]);
        }
    }

    /**
     * Creates a new Journal model.
     * For ajax request will return json object
     * and for non-ajax request if creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $request = Yii::$app->request;
        $model = new Journal();
        $model->user_id = Yii::$app->user->identity->id;

        if ($request->isAjax) {

            Yii::$app->response->format = Response::FORMAT_JSON;
            if ($model->load($request->post()) && $model->save()) {
                return [
                    'forceReload' => '#crud-datatable-pjax',
                    'title' => "Журнал",
                    'size' => 'normal',
                    'content' => '<span class="text-success">Успешно выполнено</span>',
                    'footer' => Html::button('Отмена', ['class' => 'btn btn-default pull-left', 'data-dismiss' => "modal"]) .
                        Html::a('Создать ещё', ['create'], ['class' => 'btn btn-primary', 'role' => 'modal-remote'])

                ];
            } else {
                return [
                    'title' => "Создать",
                    'size' => 'large',
                    'content' => $this->renderAjax('create', [
                        'model' => $model,
                    ]),
                    'footer' => Html::button('Отмена', ['class' => 'btn btn-default pull-left', 'data-dismiss' => "modal"]) .
                        Html::button('Сохранить', ['class' => 'btn btn-primary', 'type' => "submit"])

                ];
            }
        } else {
            /*
            *   Process for non-ajax request
            */
            if ($model->load($request->post()) && $model->save()) {
                return $this->redirect(['index']);
            } else {
                return $this->render('create', [
                    'model' => $model,
                ]);
            }
        }

    }

    /**
     * Updates an existing Journal model.
     * For ajax request will return json object
     * and for non-ajax request if update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException
     */
    public function actionUpdate($id)
    {
        $request = Yii::$app->request;
        $model = $this->findModel($id);

        if ($request->isAjax) {
            Yii::$app->response->format = Response::FORMAT_JSON;
            if ($model->load($request->post()) && $model->save()) {
                return [
                    'forceReload' => '#crud-datatable-pjax',
                    'title' => "Журнал",
                    'size' => 'large',
                    'content' => $this->renderAjax('view', [
                        'model' => $model,
                    ]),
                    'footer' => Html::button('Ок', ['class' => 'btn btn-default pull-left', 'data-dismiss' => "modal"]) .
                        Html::a('Изменить', ['update', 'id' => $id], ['class' => 'btn btn-primary', 'role' => 'modal-remote'])
                ];
            } else {
                return [
                    'title' => "Изменить",
                    'size' => 'large',
                    'content' => $this->renderAjax('update', [
                        'model' => $model,
                    ]),
                    'footer' => Html::button('Отмена', ['class' => 'btn btn-default pull-left', 'data-dismiss' => "modal"]) .
                        Html::button('Сохранить', ['class' => 'btn btn-primary', 'type' => "submit"])
                ];
            }
        } else {
            /*
            *   Process for non-ajax request
            */
            if ($model->load($request->post()) && $model->save()) {
                return $this->redirect(['index']);
            } else {
                return $this->render('update', [
                    'model' => $model,
                ]);
            }
        }
    }

    /**
     * Delete an existing Journal model.
     * For ajax request will return json object
     * and for non-ajax request if deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException
     * @throws \Exception
     * @throws \Throwable
     * @throws \yii\db\StaleObjectException
     */
    public function actionDelete($id)
    {
        $request = Yii::$app->request;
        $this->findModel($id)->delete();

        if ($request->isAjax) {
            /*
            *   Process for ajax request
            */
            Yii::$app->response->format = Response::FORMAT_JSON;
            return ['forceClose' => true, 'forceReload' => '#crud-datatable-pjax'];
        } else {
            /*
            *   Process for non-ajax request
            */
            return $this->redirect(['index']);
        }


    }

    /**
     * Delete multiple existing Journal model.
     * For ajax request will return json object
     * and for non-ajax request if deletion is successful, the browser will be redirected to the 'index' page.
     * @return mixed
     * @throws NotFoundHttpException
     * @throws \Exception
     * @throws \Throwable
     * @throws \yii\db\StaleObjectException
     */
    public function actionBulkDelete()
    {
        $request = Yii::$app->request;
        $pks = explode(',', $request->post('pks')); // Array or selected records primary keys
        foreach ($pks as $pk) {
            $model = $this->findModel($pk);
            $model->delete();
        }

        if ($request->isAjax) {
            /*
            *   Process for ajax request
            */

views/journal/_columns.php
<?php

use app\models\Journal;
use app\models\Node;
use yii\helpers\Url;

return [
    [
        'class' => 'kartik\grid\CheckboxColumn',
        'width' => '20px',
    ],
    [
        'class' => 'kartik\grid\SerialColumn',
        'width' => '30px',
    ],
    // [
    // 'class'=>'\kartik\grid\DataColumn',
    // 'attribute'=>'id',
    // ],
    [
        'class' => '\kartik\grid\DataColumn',
        'attribute' => 'object_id',
        'filter' => \app\models\OurObject::getList(),
        'value' => function (Journal $journal) {
            return $journal->objectName;
        }
    ]
    ,
    [
        'class' => '\kartik\grid\DataColumn',
        'attribute' => 'equipment_id',
        'filter' => \app\models\Equipment::getList(),
        'value' => function (Journal $journal) {
            return $journal->equipmentName;
        }
    ],
    [
        'class' => '\kartik\grid\DataColumn',
        'attribute' => 'type_id',
        'filter' => \app\models\Type::getList(),
        'value' => function (Journal $journal) {
            return $journal->typeName;
        }
    ],
    [
        'class' => '\kartik\grid\DataColumn',
        'attribute' => 'user_id',
        'filter' => Journal::getUsersList(),
        'content' => function($data){
            return $data->user->fio;
        }
    ],
    [
        'class' => '\kartik\grid\DataColumn',
        'attribute' => 'description',
    ],
    [
        'class' => '\kartik\grid\DataColumn',
        'attribute' => 'node_id',
        'label' => 'Наименование узла',
        'filter' => \app\models\Node::getList(),
        'value' => function($data){
            return Node::findOne($data->node_id)->name;
        }
    ],

    [
        'class' => '\kartik\grid\DataColumn',
        'attribute' => 'date',
//        'format' => ['date', 'Y-MM-d']
        'format' => 'date'
    ],

    // [
    // 'class'=>'\kartik\grid\DataColumn',
    // 'attribute'=>'description',
    // ],
    // [
    // 'class'=>'\kartik\grid\DataColumn',
    // 'attribute'=>'media',
    // ],
    [
        'class' => 'kartik\grid\ActionColumn',
        'dropdown' => false,
        'vAlign' => 'middle',
        'urlCreator' => function ($action, $model, $key, $index) {
            return Url::to([$action, 'id' => $key]);
        },
        'viewOptions' => ['role' => 'modal-remote', 'title' => 'Просмотр', 'data-toggle' => 'tooltip'],
        'updateOptions' => ['role' => 'modal-remote', 'title' => 'Изменить', 'data-toggle' => 'tooltip'],
        'deleteOptions' => ['role' => 'modal-remote', 'title' => 'Удалить',
            'data-confirm' => false, 'data-method' => false,// for overide yii data api
            'data-request-method' => 'post',
            'data-toggle' => 'tooltip',
            'data-confirm-title' => 'Подтвердите действие',
            'data-confirm-message' => 'Вы уверены что хотите удалить этого элемента?'],
    ],

];

views/journal/_filter_journal.php
<?php

use app\models\Equipment;
use app\models\OurObject;
use app\models\Type;
use kartik\date\DatePicker;
use kartik\form\ActiveForm;
use kartik\select2\Select2;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use yii\helpers\Url;

$request = Yii::$app->request;

$layout = <<< HTML
<div class="input-group">
    <span id="start-addon" class="input-group-addon">С</span>
    {input1}
    <span id="end-addon" class="input-group-addon" >По</span>
    {input2}
    <span class="input-group-addon kv-date-remove">
        <i class="glyphicon glyphicon-remove"></i>
    </span>
</div>
HTML;
?>
<?php $form = ActiveForm::begin([
    'options' => [
        'class' => 'hidden-print',
        'action' => '/filter-journal'
    ],
]); ?>
<div class="row">
    <div class="col-xs-6">
        <label>Период</label><br>
        <?php
        try {
            echo DatePicker::widget([
                'type' => DatePicker::TYPE_RANGE,
                'name' => 'date_start',
                'value' => $request->post('date_start'),
                'name2' => 'date_end',
                'value2' => $request->post('date_end'),
                'layout' => $layout,
                'pluginOptions' => [
                    'autoclose' => true,
                    'format' => 'dd.mm.yyyy',
                ]
            ]);
        } catch (Exception $e) {
            Yii::error($e->getTraceAsString(), __METHOD__);
            Yii::$app->session->setFlash('error', $e->getMessage());
        }
        ?>
    </div>
    <div class="col-xs-6">
        <label>Предприятие</label><br>

        <?php
        try {
            echo Select2::widget([
                'name' => 'object',
                'language' => 'ru',
                'value' => $request->post('object'),
                'data' => ArrayHelper::map(OurObject::find()->all(), 'id', 'name'),
                'options' => [
                    'placeholder' => 'Выберите предприятия',
                    'multiple' => true
                ],
                'pluginOptions' => [
                    'allowClear' => true
                ],
            ]);
        } catch (Exception $e) {
            Yii::error($e->getTraceAsString(), __METHOD__);
            Yii::$app->session->setFlash('error', $e->getMessage());
        }
        ?>
    </div>
</div>
<div class="row">
    <div class="col-xs-6">
        <label>Оборудование</label><br>
        <?php
        try {
            echo Select2::widget([
                'name' => 'equipment',
                'language' => 'ru',
                'value' => $request->post('equipment'),
                'data' => Arrayhelper::map(Equipment::find()->all(), 'id', 'name'),
//                'size' => Select2::MEDIUM,
                'options' => [
                    'placeholder' => 'Выберите оборудование',
                    'multiple' => true],
                'pluginOptions' => [
                    'allowClear' => true
                ],
            ]);
        } catch (Exception $e) {
            Yii::error($e->getTraceAsString(), __METHOD__);
            Yii::$app->session->setFlash('error', $e->getMessage());
        } ?>
    </div>
    <div class="col-xs-6">
        <label>Тип работ</label><br>
        <?php
        try {
            echo Select2::widget([
                'name' => 'type',
                'language' => 'ru',
                'value' => $request->post('type'),
                'data' => Arrayhelper::map(Type::find()->all(), 'id', 'name'),
                'options' => [
                    'placeholder' => 'Выберите оборудование',
                    'multiple' => true],
                'pluginOptions' => [
                    'allowClear' => true
                ],
            ]);
        } catch (Exception $e) {
            Yii::error($e->getTraceAsString(), __METHOD__);
            Yii::$app->session->setFlash('error', $e->getMessage());
        } ?>
    </div>
</div>
<div class="row">
    <div class="col-xs-4 pull-right">
        <div class="btn-group">
            <?= Html::a('Сбросить фильтр', Url::to('/journal/index'), ['class' => 'btn btn-warning']) ?>
            <?= Html::submitButton('Применить фильтр', ['class' => 'btn btn-info']) ?>
        </div>

    </div>
</div>
<?php ActiveForm::end(); ?>

views/journal/_form.php
<?php

use app\models\Node;
use yii\helpers\Html;
use kartik\date\DatePicker;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Journal */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="journal-form">

    <?php $form = ActiveForm::begin(); ?>

    <div class="row">
        <div class="col-md-6">
            <?= $form->field($model, 'object_id')->label()->widget(\kartik\select2\Select2::classname(), [
                'data' => \app\models\OurObject::getList(),
                'options' => [
                    //'value' =>  $model->type,
                    'placeholder' => 'Выберите предприятие',
                    'onchange' => '
                        $.post( "/journal/lists?id=' . '"+$(this).val(), function( data ){
                            $( "select#journal-equipment_id" ).html( data);
                        });
                    '
                ],
                'pluginOptions' => [
                    'allowClear' => true
                ],
            ]); ?>
        </div>
        <div class="col-md-6">
            <?= $form->field($model, 'equipment_id')->label()->widget(\kartik\select2\Select2::classname(), [
                'data' => $model->getEquipmentList($model->object_id),//\app\models\Equipment::getList(),
                'options' => [
                    'placeholder' => 'Выберите оборудование',
                ],
                'pluginOptions' => [
                    'allowClear' => true
                ],
            ]); ?>
        </div>
    </div>

    <div class="row">
        <div class="col-md-4">
            <?= $form->field($model, 'date')->widget(DatePicker::classname(), [
                'options' => [
                    'placeholder' => 'Выберите',
                    'value' => date("Y-m-d", strtotime($model->date)),
                ],
                'layout' => '{picker}{input}',
                'pluginOptions' => [
                    'autoclose' => true,
                    'format' => 'yyyy-mm-dd',
                    //'startView'=>'year',
                ]
            ]) ?>
        </div>
        <div class="col-md-4">
            <?= $form->field($model, 'type_id')->dropDownList(
                \app\models\Type::getList(),
                [
                    'prompt' => 'Выберите тип...'
                ]);
            ?>
        </div>
        <div class="col-md-4">
            <?= $form->field($model, 'media')->textInput(['maxlength' => true]) ?>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <?= $form->field($model, 'description')->textarea(['rows' => '3']) ?>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">

            <?= $form->field($model, 'node_id')->dropDownList(
                Node::getList(),
                [
                    'prompt' => 'Выберите узел...'
                ])->label('Наименование узла');
            ?>
        </div>
    </div>


    <?= $form->field($model, 'user_id')
        ->hiddenInput(['value' => Yii::$app->user->identity->id])->label(false); ?>

    <?php if (!Yii::$app->request->isAjax) { ?>
        <div class="form-group">
            <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
        </div>
    <?php } ?>

    <?php ActiveForm::end(); ?>
</div>

<script>
    $(document).ready(function () {
        $('#journal-object_id').change(function () {
            //$('#journal-equipment_id option').hide();
            $('select').find('.equipment_object_' + $('#journal-object_id').val()).show();
        });
    });
</script>

views/journal/_import_form.php
<?php

use kartik\file\FileInput;
use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="import-payment-form">
    <?php $form = ActiveForm::begin(['options' => ['enctype' => 'multipart/form-data']]); ?>

    <div class="row" style="display: flex; align-items: center;">
        <div class="col-md-12">
            <?= $form->field($model, 'file')->widget(FileInput::classname([
                'options' => ['multiple' => true],
            ]))->label('Выберите файл для импорта'); ?>
        </div>
    </div>
    <?php if (!Yii::$app->request->isAjax) { ?>
        <div class="form-group">
            <?= Html::submitButton('Импортировать', ['class' => 'btn btn-primary']) ?>
        </div>
    <?php } ?>

    <?php ActiveForm::end(); ?>

</div>

views/journal/create.php
<?php


/* @var $this yii\web\View */
/* @var $model app\models\Journal */

?>
<div class="journal-create">
    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>
</div>

views/journal/import.php
<?php

/* @var $this yii\web\View */

?>
<div class="payment-create">
    <?= $this->render('_import_form', ['model' => $model]) ?>
</div>

views/journal/index.php
<?php

use app\models\User;
use johnitvn\ajaxcrud\CrudAsset;
use kartik\grid\GridView;
use moonland\phpexcel\Excel;
use yii\bootstrap\Modal;
use yii\helpers\Html;
use yii\helpers\Url;

/* @var array $post Массив параметров для полей фильтра */
/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */
/* @var $dataProvider_export yii\data\ActiveDataProvider */
/* @var $searchModel app\models\JournalSearch */

$this->title = 'Журнал';
$this->params['breadcrumbs'][] = $this->title;

CrudAsset::register($this);

$import_btn = Html::a('Импорт из файла', ['/journal/upload'], [
    'role' => 'modal-remote',
    'title' => 'View',
    'data-toggle' => 'tooltip',
    'class' => 'btn btn-primary',
]);

if (!User::isAdmin()) {
    $import_btn = '';
}
?>

<div class="container journal-filter">
    <?= $this->render('_filter_journal', ['post' => $post]) ?>
</div>
<div class="journal-index">
    <div id="ajaxCrudDatatable">
        <?php try {
            echo GridView::widget([
                'id' => 'crud-datatable',
                'dataProvider' => $dataProvider,
                'filterModel' => $searchModel,
                'pjax' => true,
                'columns' => require(__DIR__ . '/_columns.php'),
                'toolbar' => [
                    ['content' =>
                        Html::a('Создать', ['create'],
                            ['role' => 'modal-remote', 'title' => 'Создать', 'class' => 'btn btn-primary']) .
                        Html::a('<i class="glyphicon glyphicon-repeat"></i>', [''],
                            ['data-pjax' => 1, 'class' => 'btn btn-default', 'title' => 'Обновить']) .
                        '{toggleData}'
                        .'{export}'
                    ],
                ],
                'exportConfig' => [
                    GridView::EXCEL => [
                        'label' => 'Сохранить в EXCEL',
                        'filename' => 'Журнал_Excel',
                        'mime' => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
                        'extension' => 'xlsx',

                    ],
                    GridView::CSV => [
                        'label' => 'Сохранить в CSV',
                        'filename' => 'Журнал_CSV',
                        'colDelemiter' => ';'
                    ],
                ],
                'export' => [
                    'target' => '_self',
                    'showConfirmAlert' => false,
                    'fontAwesome' => true,
                ],
                'striped' => true,
                'condensed' => true,
                'responsive' => true,
                'panel' => [
                    'type' => 'primary',
                    'heading' => '<i class="glyphicon glyphicon-list"></i> Список',
                    'before' => $import_btn,
                    '<div class="clearfix"></div>',
                ]
            ]);
        } catch (Exception $e) {
            Yii::error($e->getTraceAsString(), __METHOD__);
            Yii::$app->session->setFlash('error', $e->getMessage());
        } ?>
    </div>

</div>
<?php Modal::begin([
    "id" => "ajaxCrudModal",
    "footer" => "",// always need it for jquery plugin
]) ?>
<?php Modal::end(); ?>

views/journal/update.php
<?php

/* @var $this yii\web\View */
/* @var $model app\models\Journal */
?>
<div class="journal-update">

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/journal/view.php
<?php

use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Journal */
?>
<div class="journal-view">

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            //'object_id',
            'objectName',
            //'equipment_id',
            'equipmentName',
            //'user_id',
            'date',
            //'type_id',
            [
                'attribute' => 'type_id',
                'value' => $model->type->name,
            ],
            'description',
            'media',
            'node_id',
            [
                'attribute' => 'node_id',
                'value' => $model->node->name,
                'label' => 'Наименование узла'
            ]
        ],
    ]) ?>

</div>